CFLAGS += -g -Wall
LDFLAGS += -lm

CC=$(CROSS_COMPILE)gcc

all: plget

ALL_SOURCES:=$(wildcard *.c)

plget: %: $(ALL_SOURCES:.c=.o)
	@echo "CC " $@
	@$(CC) -o $@ $^ $(LDFLAGS)

# Option -MD needed to generate .d files in order to include them
%.o: %.c
	@echo "CC " $@
	@$(CC) -c -MD $< -o $@ $(CFLAGS)

#include targets for all headers, generated by -MD command
include $(wildcard *.d)

clean:
	rm -f *.o *.d plget

distclean: clean
	rm -rf cscope* tags

.PHONY: clean distclean
